name: blockchain_voting_client
description: Blockchain based voting system
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  web3dart: ^2.7.1
  http: ^1.2.0

flutter:
  uses-material-design: true
